markdown: kramdown
theme: minima

gems:
  - jekyll-feed
  
title: Philip Cowperthwaite Astronomy
name: Philip Cowperthwaite
description: Connecting Gravitational Wave and Electromagnetic Astronomy

# Includes an icon in the footer for each username you enter
footer-links:
  email: pcowpert@cfa.harvard.edu
  github: pcowpert
  twitter: PCowperthwaite
  rss: pcowpert

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://pcowpert.github.io

# Exclude these files from your production _site
exclude:
    - LICENSE
    - README.md
